
import { SupportedLanguage, TranslationKey } from './types';

export const TRANSLATIONS: Record<SupportedLanguage, Record<TranslationKey, string>> = {
  [SupportedLanguage.EN]: {
    nav_home: 'Home',
    nav_calculator: 'Fair Price Calculator',
    nav_complaints: 'Complaint Box',
    nav_login: 'Login',
    nav_logout: 'Logout',
    nav_about: 'About Us',
    hero_title: 'Empowering Farmers with Fair Pricing',
    hero_subtitle: 'Calculate the true value of your hard work and protect your rights against unfair trade practices.',
    hero_cta: 'Calculate Price Now',
    auth_login_title: 'Farmer Login',
    auth_signup_title: 'Farmer Registration',
    auth_username: 'Full Name',
    auth_mobile: 'Mobile Number',
    auth_otp: 'Enter OTP',
    auth_get_otp: 'Get OTP',
    auth_verify: 'Verify & Login',
    auth_switch_signup: 'New user? Register here',
    auth_switch_login: 'Already have an account? Login',
    calc_title: 'Fair Crop Price Calculator',
    calc_crop_name: 'Crop Name (e.g., Wheat, Rice)',
    calc_quantity: 'Quantity (Quintals)',
    calc_quality: 'Quality Grade',
    calc_region: 'Region/State',
    calc_cost_seeds: 'Seed Cost (₹)',
    calc_cost_fertilizer: 'Fertilizer/Pesticide Cost (₹)',
    calc_cost_labour: 'Labour Cost (₹)',
    calc_cost_maint: 'Maintenance Cost (₹)',
    calc_cost_other: 'Other Costs (Transport etc.) (₹)',
    calc_total_cost_label: 'Total Calculated Cost',
    calc_market_rate: 'Current Market Rate Offer (₹)',
    calc_button: 'Calculate Fair Price',
    comp_title: 'Report Unfair Traders',
    comp_trader: 'Trader Name/Agency',
    comp_issue: 'Describe the Issue',
    comp_submit: 'File Complaint',
    comp_history: 'Your Complaint History',
    about_title: 'Our Mission & Story',
    about_mission: 'AgriFair is dedicated to eliminating the information gap between farmers and the market. We believe every farmer deserves a fair price for their hard work. By using advanced AI to calculate real-world costs, we empower you to negotiate better.',
    about_interview_title: 'Voices from the Field: Interview with Ram Kishan',
    about_q1: 'Ram Kishan ji, what was your biggest challenge before using AgriFair?',
    about_a1: 'I used to sell my wheat at whatever price the local middleman offered. I didn\'t know the real market rate in the city mandi. I often incurred losses despite a good harvest.',
    about_q2: 'How has the situation changed now?',
    about_a2: 'Now I calculate the cost on my phone. When the trader offers a low price, I show him the calculation. Last season, I negotiated a 15% higher rate because I had the data.',
    about_q3: 'What is your message to other farmers?',
    about_a3: 'Don\'t sell in the dark. Know your cost, know your worth. Unity and information are our biggest tools.',
    about_team_title: 'Our Dedicated Team',
    about_team_desc: 'Our team on the field in Ramanagara, Karnataka, working directly with farmers to understand their needs.',
  },
  [SupportedLanguage.HI]: {
    nav_home: 'होम',
    nav_calculator: 'उचित मूल्य कैलकुलेटर',
    nav_complaints: 'शिकायत पेटी',
    nav_login: 'लॉगिन',
    nav_logout: 'लॉगआउट',
    nav_about: 'हमारे बारे में',
    hero_title: 'किसानों को उचित मूल्य के साथ सशक्त बनाना',
    hero_subtitle: 'अपनी मेहनत के सही मूल्य की गणना करें और अनुचित व्यापार प्रथाओं के खिलाफ अपने अधिकारों की रक्षा करें।',
    hero_cta: 'मूल्य की गणना करें',
    auth_login_title: 'किसान लॉगिन',
    auth_signup_title: 'किसान पंजीकरण',
    auth_username: 'पूरा नाम',
    auth_mobile: 'मोबाइल नंबर',
    auth_otp: 'ओटीपी दर्ज करें',
    auth_get_otp: 'ओटीपी प्राप्त करें',
    auth_verify: 'सत्यापित करें और लॉगिन करें',
    auth_switch_signup: 'नए उपयोगकर्ता? यहाँ रजिस्टर करें',
    auth_switch_login: 'पहले से खाता है? लॉगिन करें',
    calc_title: 'फसल उचित मूल्य कैलकुलेटर',
    calc_crop_name: 'फसल का नाम (जैसे, गेहूं, चावल)',
    calc_quantity: 'मात्रा (क्विंटल)',
    calc_quality: 'गुणवत्ता ग्रेड',
    calc_region: 'क्षेत्र / राज्य',
    calc_cost_seeds: 'बीज की लागत (₹)',
    calc_cost_fertilizer: 'खाद/उर्वरक की लागत (₹)',
    calc_cost_labour: 'मजदूरी की लागत (₹)',
    calc_cost_maint: 'रखरखाव की लागत (₹)',
    calc_cost_other: 'अन्य खर्च (परिवहन आदि) (₹)',
    calc_total_cost_label: 'कुल गणना लागत',
    calc_market_rate: 'वर्तमान बाजार दर प्रस्ताव (₹)',
    calc_button: 'उचित मूल्य की गणना करें',
    comp_title: 'अनुचित व्यापारियों की रिपोर्ट करें',
    comp_trader: 'व्यापारी का नाम / एजेंसी',
    comp_issue: 'समस्या का वर्णन करें',
    comp_submit: 'शिकायत दर्ज करें',
    comp_history: 'आपकी शिकायत का इतिहास',
    about_title: 'हमारा मिशन और कहानी',
    about_mission: 'AgriFair किसानों और बाजार के बीच सूचना के अंतर को खत्म करने के लिए समर्पित है। हमारा मानना है कि हर किसान अपनी मेहनत के लिए उचित मूल्य का हकदार है।',
    about_interview_title: 'खेत से आवाज: राम किशन जी के साथ साक्षात्कार',
    about_q1: 'राम किशन जी, AgriFair का उपयोग करने से पहले आपकी सबसे बड़ी चुनौती क्या थी?',
    about_a1: 'मैं अपना गेहूं उस कीमत पर बेचता था जो स्थानीय बिचौलिया देता था। मुझे शहर की मंडी का असली भाव नहीं पता था। अच्छी फसल के बावजूद मुझे अक्सर नुकसान होता था।',
    about_q2: 'अब स्थिति कैसे बदल गई है?',
    about_a2: 'अब मैं अपने फोन पर लागत की गणना करता हूं। जब व्यापारी कम कीमत देता है, तो मैं उसे हिसाब दिखाता हूं। पिछले सीजन में, मेरे पास डेटा होने के कारण मैंने 15% अधिक दर पर सौदा किया।',
    about_q3: 'अन्य किसानों के लिए आपका क्या संदेश है?',
    about_a3: 'अंधेरे में मत बेचो। अपनी लागत जानो, अपनी कीमत जानो। एकता और जानकारी हमारे सबसे बड़े हथियार हैं।',
    about_team_title: 'हमारी समर्पित टीम',
    about_team_desc: 'रामநகर, कर्नाटक में हमारी टीम, किसानों की जरूरतों को समझने के लिए सीधे उनके साथ काम कर रही है।',
  },
  [SupportedLanguage.KN]: {
    nav_home: 'ಮುಖಪುಟ',
    nav_calculator: 'ನ್ಯಾಯಯುತ ಬೆಲೆ ಲೆಕ್ಕಾಚಾರ',
    nav_complaints: 'ದೂರು ಪೆಟ್ಟಿಗೆ',
    nav_login: 'ಲಾಗಿನ್',
    nav_logout: 'ಲಾಗೌಟ್',
    nav_about: 'ನಮ್ಮ ಬಗ್ಗೆ',
    hero_title: 'ರೈತರನ್ನು ನ್ಯಾಯಯುತ ಬೆಲೆಯೊಂದಿಗೆ ಸಬಲೀಕರಣಗೊಳಿಸುವುದು',
    hero_subtitle: 'ನಿಮ್ಮ ಶ್ರಮದ ನಿಜವಾದ ಮೌಲ್ಯವನ್ನು ಲೆಕ್ಕಹಾಕಿ ಮತ್ತು ಅನ್ಯಾಯದ ವ್ಯಾಪಾರ ಪದ್ಧತಿಗಳ ವಿರುದ್ಧ ನಿಮ್ಮ ಹಕ್ಕುಗಳನ್ನು ರಕ್ಷಿಸಿ.',
    hero_cta: 'ಬೆಲೆಯನ್ನು ಲೆಕ್ಕಹಾಕಿ',
    auth_login_title: 'ರೈತರ ಲಾಗಿನ್',
    auth_signup_title: 'ರೈತರ ನೋಂದಣಿ',
    auth_username: 'ಪೂರ್ಣ ಹೆಸರು',
    auth_mobile: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    auth_otp: 'OTP ನಮೂದಿಸಿ',
    auth_get_otp: 'OTP ಪಡೆಯಿರಿ',
    auth_verify: 'ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಲಾಗಿನ್ ಮಾಡಿ',
    auth_switch_signup: 'ಹೊಸ ಬಳಕೆದಾರರೆ? ಇಲ್ಲಿ ನೋಂದಾಯಿಸಿ',
    auth_switch_login: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ',
    calc_title: 'ಬೆಳೆ ನ್ಯಾಯಯುತ ಬೆಲೆ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
    calc_crop_name: 'ಬೆಳೆಯ ಹೆಸರು (ಉದಾ. ಗೋಧಿ, ಅಕ್ಕಿ)',
    calc_quantity: 'ಪ್ರಮಾಣ (ಕ್ವಿಂಟಾಲ್)',
    calc_quality: 'ಗುಣಮಟ್ಟದ ಶ್ರೇಣಿ',
    calc_region: 'ಪ್ರದೇಶ / ರಾಜ್ಯ',
    calc_cost_seeds: 'ಬೀಜದ ವೆಚ್ಚ (₹)',
    calc_cost_fertilizer: 'ಗೊಬ್ಬರದ ವೆಚ್ಚ (₹)',
    calc_cost_labour: 'ಕೂಲಿ ವೆಚ್ಚ (₹)',
    calc_cost_maint: 'ನಿರ್ವಹಣೆ ವೆಚ್ಚ (₹)',
    calc_cost_other: 'ಇತರೆ ವೆಚ್ಚಗಳು (ಸಾರಿಗೆ ಇತ್ಯಾದಿ) (₹)',
    calc_total_cost_label: 'ಒಟ್ಟು ಲೆಕ್ಕಹಾಕಿದ ವೆಚ್ಚ',
    calc_market_rate: 'ಪ್ರಸ್ತುತ ಮಾರುಕಟ್ಟೆ ದರ (₹)',
    calc_button: 'ನ್ಯಾಯಯುತ ಬೆಲೆಯನ್ನು ಲೆಕ್ಕಹಾಕಿ',
    comp_title: 'ಅನ್ಯಾಯದ ವ್ಯಾಪಾರಿಗಳ ಬಗ್ಗೆ ವರದಿ ಮಾಡಿ',
    comp_trader: 'ವ್ಯಾಪಾರಿ ಹೆಸರು / ಏಜೆನ್ಸಿ',
    comp_issue: 'ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ',
    comp_submit: 'ದೂರು ದಾಖಲಿಸಿ',
    comp_history: 'ನಿಮ್ಮ ದೂರಿನ ಇತಿಹಾಸ',
    about_title: 'ನಮ್ಮ ಮಿಷನ್ ಮತ್ತು ಕಥೆ',
    about_mission: 'AgriFair ರೈತರು ಮತ್ತು ಮಾರುಕಟ್ಟೆಯ ನಡುವಿನ ಮಾಹಿತಿಯ ಅಂತರವನ್ನು ಹೋಗಲಾಡಿಸಲು ಸಮರ್ಪಿತವಾಗಿದೆ. ಪ್ರತಿಯೊಬ್ಬ ರೈತನು ತನ್ನ ಶ್ರಮಕ್ಕೆ ತಕ್ಕ ನ್ಯಾಯಯುತ ಬೆಲೆಯನ್ನು ಪಡೆಯಲು ಅರ್ಹ ಎಂದು ನಾವು ನಂಬುತ್ತೇವೆ.',
    about_interview_title: 'ಕ್ಷೇತ್ರದ ಧ್ವನಿಗಳು: ರಾಮ್ ಕಿಶನ್ ಅವರೊಂದಿಗೆ ಸಂದರ್ಶನ',
    about_q1: 'ರಾಮ್ ಕಿಶನ್ ಜೀ, AgriFair ಬಳಸುವ ಮೊದಲು ನಿಮ್ಮ ದೊಡ್ಡ ಸವಾಲು ಏನಾಗಿತ್ತು?',
    about_a1: 'ಸ್ಥಳೀಯ ಮಧ್ಯವರ್ತಿ ನೀಡುವ ಬೆಲೆಗೆ ನಾನು ನನ್ನ ಗೋಧಿಯನ್ನು ಮಾರುತ್ತಿದ್ದೆ. ನಗರದ ಮಂಡಿಯ ನಿಜವಾದ ದರ ನನಗೆ ತಿಳಿದಿರಲಿಲ್ಲ. ಉತ್ತಮ ಬೆಳೆಯ ಹೊರತಾಗಿಯೂ ನಾನು ನಷ್ಟ ಅನುಭವಿಸುತ್ತಿದ್ದೆ.',
    about_q2: 'ಈಗ ಪರಿಸ್ಥಿತಿ ಹೇಗೆ ಬದಲಾಗಿದೆ?',
    about_a2: 'ಈಗ ನಾನು ಫೋನ್‌ನಲ್ಲಿ ವೆಚ್ಚವನ್ನು ಲೆಕ್ಕ ಹಾಕುತ್ತೇನೆ. ವ್ಯಾಪಾರಿ ಕಡಿಮೆ ಬೆಲೆ ನೀಡಿದಾಗ, ನಾನು ಅವರಿಗೆ ಲೆಕ್ಕ ತೋರಿಸುತ್ತೇನೆ. ಕಳೆದ ಋತುವಿನಲ್ಲಿ, ನನ್ನ ಬಳಿ ಮಾಹಿತಿ ಇದ್ದುದರಿಂದ ನಾನು 15% ಹೆಚ್ಚಿನ ದರವನ್ನು ಪಡೆದೆ.',
    about_q3: 'ಇತರ ರೈತರಿಗೆ ನಿಮ್ಮ ಸಂದೇಶವೇನು?',
    about_a3: 'ಕತ್ತಲೆಯಲ್ಲಿ ಮಾರಾಟ ಮಾಡಬೇಡಿ. ನಿಮ್ಮ ವೆಚ್ಚವನ್ನು ತಿಳಿದುಕೊಳ್ಳಿ, ನಿಮ್ಮ ಮೌಲ್ಯವನ್ನು ತಿಳಿದುಕೊಳ್ಳಿ. ಒಗ್ಗಟ್ಟು ಮತ್ತು ಮಾಹಿತಿಯೇ ನಮ್ಮ ದೊಡ್ಡ ಅಸ್ತ್ರ.',
    about_team_title: 'ನಮ್ಮ ಸಮರ್ಪಿತ ತಂಡ',
    about_team_desc: 'ರಾಮನಗರ, ಕರ್ನಾಟಕದಲ್ಲಿ ನಮ್ಮ ತಂಡ, ರೈತರ ಅಗತ್ಯಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಅವರೊಂದಿಗೆ ನೇರವಾಗಿ ಕೆಲಸ ಮಾಡುತ್ತಿದೆ.',
  }
};