
import { SupportedLanguage, TranslationKey } from './types';

export const TRANSLATIONS: Record<SupportedLanguage, Record<TranslationKey, string>> = {
  [SupportedLanguage.EN]: {
    nav_home: 'Home',
    nav_calculator: 'Fair Price Calculator',
    nav_complaints: 'Complaint Box',
    nav_login: 'Login',
    nav_logout: 'Logout',
    hero_title: 'Empowering Farmers with Fair Pricing',
    hero_subtitle: 'Calculate the true value of your hard work and protect your rights against unfair trade practices.',
    hero_cta: 'Calculate Price Now',
    auth_login_title: 'Farmer Login',
    auth_signup_title: 'Farmer Registration',
    auth_username: 'Full Name',
    auth_mobile: 'Mobile Number',
    auth_otp: 'Enter OTP',
    auth_get_otp: 'Get OTP',
    auth_verify: 'Verify & Login',
    auth_switch_signup: 'New user? Register here',
    auth_switch_login: 'Already have an account? Login',
    calc_title: 'Fair Crop Price Calculator',
    calc_crop_name: 'Crop Name (e.g., Wheat, Rice)',
    calc_quantity: 'Quantity (Quintals)',
    calc_quality: 'Quality Grade',
    calc_region: 'Region/State',
    calc_cost_seeds: 'Seed Cost (₹)',
    calc_cost_fertilizer: 'Fertilizer/Pesticide Cost (₹)',
    calc_cost_labour: 'Labour Cost (₹)',
    calc_cost_maint: 'Maintenance Cost (₹)',
    calc_cost_other: 'Other Costs (Transport etc.) (₹)',
    calc_total_cost_label: 'Total Calculated Cost',
    calc_market_rate: 'Current Market Rate Offer (₹)',
    calc_button: 'Calculate Fair Price',
    comp_title: 'Report Unfair Traders',
    comp_trader: 'Trader Name/Agency',
    comp_issue: 'Describe the Issue',
    comp_submit: 'File Complaint',
    comp_history: 'Your Complaint History',
  },
  [SupportedLanguage.HI]: {
    nav_home: 'होम',
    nav_calculator: 'उचित मूल्य कैलकुलेटर',
    nav_complaints: 'शिकायत पेटी',
    nav_login: 'लॉगिन',
    nav_logout: 'लॉगआउट',
    hero_title: 'किसानों को उचित मूल्य के साथ सशक्त बनाना',
    hero_subtitle: 'अपनी मेहनत के सही मूल्य की गणना करें और अनुचित व्यापार प्रथाओं के खिलाफ अपने अधिकारों की रक्षा करें।',
    hero_cta: 'मूल्य की गणना करें',
    auth_login_title: 'किसान लॉगिन',
    auth_signup_title: 'किसान पंजीकरण',
    auth_username: 'पूरा नाम',
    auth_mobile: 'मोबाइल नंबर',
    auth_otp: 'ओटीपी दर्ज करें',
    auth_get_otp: 'ओटीपी प्राप्त करें',
    auth_verify: 'सत्यापित करें और लॉगिन करें',
    auth_switch_signup: 'नए उपयोगकर्ता? यहाँ रजिस्टर करें',
    auth_switch_login: 'पहले से खाता है? लॉगिन करें',
    calc_title: 'फसल उचित मूल्य कैलकुलेटर',
    calc_crop_name: 'फसल का नाम (जैसे, गेहूं, चावल)',
    calc_quantity: 'मात्रा (क्विंटल)',
    calc_quality: 'गुणवत्ता ग्रेड',
    calc_region: 'क्षेत्र / राज्य',
    calc_cost_seeds: 'बीज की लागत (₹)',
    calc_cost_fertilizer: 'खाद/उर्वरक की लागत (₹)',
    calc_cost_labour: 'मजदूरी की लागत (₹)',
    calc_cost_maint: 'रखरखाव की लागत (₹)',
    calc_cost_other: 'अन्य खर्च (परिवहन आदि) (₹)',
    calc_total_cost_label: 'कुल गणना लागत',
    calc_market_rate: 'वर्तमान बाजार दर प्रस्ताव (₹)',
    calc_button: 'उचित मूल्य की गणना करें',
    comp_title: 'अनुचित व्यापारियों की रिपोर्ट करें',
    comp_trader: 'व्यापारी का नाम / एजेंसी',
    comp_issue: 'समस्या का वर्णन करें',
    comp_submit: 'शिकायत दर्ज करें',
    comp_history: 'आपकी शिकायत का इतिहास',
  },
  [SupportedLanguage.KN]: {
    nav_home: 'ಮುಖಪುಟ',
    nav_calculator: 'ನ್ಯಾಯಯುತ ಬೆಲೆ ಲೆಕ್ಕಾಚಾರ',
    nav_complaints: 'ದೂರು ಪೆಟ್ಟಿಗೆ',
    nav_login: 'ಲಾಗಿನ್',
    nav_logout: 'ಲಾಗೌಟ್',
    hero_title: 'ರೈತರನ್ನು ನ್ಯಾಯಯುತ ಬೆಲೆಯೊಂದಿಗೆ ಸಬಲೀಕರಣಗೊಳಿಸುವುದು',
    hero_subtitle: 'ನಿಮ್ಮ ಶ್ರಮದ ನಿಜವಾದ ಮೌಲ್ಯವನ್ನು ಲೆಕ್ಕಹಾಕಿ ಮತ್ತು ಅನ್ಯಾಯದ ವ್ಯಾಪಾರ ಪದ್ಧತಿಗಳ ವಿರುದ್ಧ ನಿಮ್ಮ ಹಕ್ಕುಗಳನ್ನು ರಕ್ಷಿಸಿ.',
    hero_cta: 'ಬೆಲೆಯನ್ನು ಲೆಕ್ಕಹಾಕಿ',
    auth_login_title: 'ರೈತರ ಲಾಗಿನ್',
    auth_signup_title: 'ರೈತರ ನೋಂದಣಿ',
    auth_username: 'ಪೂರ್ಣ ಹೆಸರು',
    auth_mobile: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    auth_otp: 'OTP ನಮೂದಿಸಿ',
    auth_get_otp: 'OTP ಪಡೆಯಿರಿ',
    auth_verify: 'ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಲಾಗಿನ್ ಮಾಡಿ',
    auth_switch_signup: 'ಹೊಸ ಬಳಕೆದಾರರೆ? ಇಲ್ಲಿ ನೋಂದಾಯಿಸಿ',
    auth_switch_login: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ',
    calc_title: 'ಬೆಳೆ ನ್ಯಾಯಯುತ ಬೆಲೆ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
    calc_crop_name: 'ಬೆಳೆಯ ಹೆಸರು (ಉದಾ. ಗೋಧಿ, ಅಕ್ಕಿ)',
    calc_quantity: 'ಪ್ರಮಾಣ (ಕ್ವಿಂಟಾಲ್)',
    calc_quality: 'ಗುಣಮಟ್ಟದ ಶ್ರೇಣಿ',
    calc_region: 'ಪ್ರದೇಶ / ರಾಜ್ಯ',
    calc_cost_seeds: 'ಬೀಜದ ವೆಚ್ಚ (₹)',
    calc_cost_fertilizer: 'ಗೊಬ್ಬರದ ವೆಚ್ಚ (₹)',
    calc_cost_labour: 'ಕೂಲಿ ವೆಚ್ಚ (₹)',
    calc_cost_maint: 'ನಿರ್ವಹಣೆ ವೆಚ್ಚ (₹)',
    calc_cost_other: 'ಇತರೆ ವೆಚ್ಚಗಳು (ಸಾರಿಗೆ ಇತ್ಯಾದಿ) (₹)',
    calc_total_cost_label: 'ಒಟ್ಟು ಲೆಕ್ಕಹಾಕಿದ ವೆಚ್ಚ',
    calc_market_rate: 'ಪ್ರಸ್ತುತ ಮಾರುಕಟ್ಟೆ ದರ (₹)',
    calc_button: 'ನ್ಯಾಯಯುತ ಬೆಲೆಯನ್ನು ಲೆಕ್ಕಹಾಕಿ',
    comp_title: 'ಅನ್ಯಾಯದ ವ್ಯಾಪಾರಿಗಳ ಬಗ್ಗೆ ವರದಿ ಮಾಡಿ',
    comp_trader: 'ವ್ಯಾಪಾರಿ ಹೆಸರು / ಏಜೆನ್ಸಿ',
    comp_issue: 'ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ',
    comp_submit: 'ದೂರು ದಾಖಲಿಸಿ',
    comp_history: 'ನಿಮ್ಮ ದೂರಿನ ಇತಿಹಾಸ',
  }
};
